# Lab | Data Structuring and Combining Data

## Challenge 1: Combining & Cleaning Data

In this challenge, we will be working with the customer data from an insurance company, as we did in the two previous labs. The data can be found here:
- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv

But this time, we got new data, which can be found in the following 2 CSV files located at the links below.

- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file2.csv
- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file3.csv

Note that you'll need to clean and format the new data.

Observation:
- One option is to first combine the three datasets and then apply the cleaning function to the new combined dataset
- Another option would be to read the clean file you saved in the previous lab, and just clean the two new files and concatenate the three clean datasets

In [2]:
import pandas as pd

In [3]:
url_1 = "https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv"
url_2 = "https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file2.csv"
url_3 = "https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file3.csv"

In [4]:
df_1 = pd.read_csv(url_1)
df_2 = pd.read_csv(url_2)
df_3 = pd.read_csv(url_3)

In [5]:
df_1.head()

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323

In [6]:
df_2.head()

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Total Claim Amount,Policy Type,Vehicle Class
0,GS98873,Arizona,F,Bachelor,323912.47%,16061,88,1/0/00,633.6,Personal Auto,Four-Door Car
1,CW49887,California,F,Master,462680.11%,79487,114,1/0/00,547.2,Special Auto,SUV
2,MY31220,California,F,College,899704.02%,54230,112,1/0/00,537.6,Personal Auto,Two-Door Car
3,UH35128,Oregon,F,College,2580706.30%,71210,214,1/1/00,1027.2,Personal Auto,Luxury Car
4,WH52799,Arizona,F,College,380812.21%,94903,94,1/0/00,451.2,Corporate Auto,Two-Door Car

In [7]:
df_3.head()

,Customer,State,Customer Lifetime Value,Education,Gender,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Total Claim Amount,Vehicle Class
0,SA25987,Washington,3479.137523,High School or Below,M,0,104,0,Personal Auto,499.200000,Two-Door Car
1,TB86706,Arizona,2502.637401,Master,M,0,66,0,Personal Auto,3.468912,Two-Door Car
2,ZL73902,Nevada,3265.156348,Bachelor,F,25820,82,0,Personal Auto,393.600000,Four-Door Car
3,KX23516,California,4455.843406,High School or Below,F,0,121,0,Personal Auto,699.615192,SUV
4,FN77294,California,7704.958480,High School or Below,M,30366,101,2,Personal Auto,484.800000,SUV

In [8]:
df_1.shape

(4008, 11)

In [9]:
df_2.shape

(996, 11)

In [10]:
df_3.shape

(7070, 11)

In [11]:
df_1.columns = df_1.columns.str.lower().str.replace(" ", "_")
df_2.columns = df_2.columns.str.lower().str.replace(" ", "_")
df_3.columns = df_3.columns.str.lower().str.replace(" ", "_")

In [12]:
df_1.columns
df_2.columns
df_3.columns

Index(['customer', 'state', 'customer_lifetime_value', 'education', 'gender',
       'income', 'monthly_premium_auto', 'number_of_open_complaints',
       'policy_type', 'total_claim_amount', 'vehicle_class'],
      dtype='str')

In [13]:
df_3 = df_3.rename(columns={"state": "st"})

In [14]:
df_3.columns

Index(['customer', 'st', 'customer_lifetime_value', 'education', 'gender',
       'income', 'monthly_premium_auto', 'number_of_open_complaints',
       'policy_type', 'total_claim_amount', 'vehicle_class'],
      dtype='str')

In [15]:
df = pd.concat([df_1, df_2, df_3], ignore_index=True)

In [16]:
df.head()

,customer,st,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12074 entries, 0 to 12073
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customer                   9137 non-null   str
 1   st                         9137 non-null   str
 2   gender                     9015 non-null   str
 3   education                  9137 non-null   str
 4   customer_lifetime_value    9130 non-null   object
 5   income                     9137 non-null   float64
 6   monthly_premium_auto       9137 non-null   float64
 7   number_of_open_complaints  9137 non-null   object
 8   policy_type                9137 non-null   str
 9   vehicle_class              9137 non-null   str
 10  total_claim_amount         9137 non-null   float64
dtypes: float64(3), object(2), str(6)
memory usage: 1.0+ MB

In [18]:
df.shape

(12074, 11)

In [19]:
df["customer_lifetime_value"].head()

0            NaN
1     697953.59%
2    1288743.17%
3     764586.18%
4     536307.65%
Name: customer_lifetime_value, dtype: object

In [21]:
df["customer_lifetime_value"] = df["customer_lifetime_value"].astype(str).str.replace("%", "")
df["customer_lifetime_value"] = pd.to_numeric(df["customer_lifetime_value"], errors="coerce")
df.head()

,customer,st,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323

In [22]:
df["number_of_open_complaints"].unique()
df["number_of_open_complaints"] = df["number_of_open_complaints"].astype(str).str.split("/").str[1]
df["number_of_open_complaints"] = pd.to_numeric(
    df["number_of_open_complaints"],
    errors="coerce"
)

In [23]:
df.duplicated().sum()

np.int64(2939)

In [24]:
df = df.drop_duplicates()
df = df.reset_index(drop=True)

In [25]:
df.isnull().sum()

customer                        1
st                              1
gender                        123
education                       1
customer_lifetime_value         8
income                          1
monthly_premium_auto            1
number_of_open_complaints    7071
policy_type                     1
vehicle_class                   1
total_claim_amount              1
dtype: int64

In [26]:
#Rellenar los nulos con valores
df["gender"] = df["gender"].fillna(df["gender"].mode()[0])
df["customer_lifetime_value"] = df["customer_lifetime_value"].fillna(df["customer_lifetime_value"].median())

In [27]:
df.to_csv("clean_customer_data.csv", index=False)

# Challenge 2: Structuring Data

In this challenge, we will continue to work with customer data from an insurance company, but we will use a dataset with more columns, called marketing_customer_analysis.csv, which can be found at the following link:

https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis_clean.csv

This dataset contains information such as customer demographics, policy details, vehicle information, and the customer's response to the last marketing campaign. Our goal is to explore and analyze this data by performing data cleaning, formatting, and structuring.

In [28]:
#Cargar el dataset
url = "https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis_clean.csv"

marketing = pd.read_csv(url)

In [29]:
#Explorar dataset
marketing.head()

,unnamed:_0,customer,state,customer_lifetime_value,response,coverage,education,effective_to_date,employmentstatus,gender,...,number_of_policies,policy_type,policy,renew_offer_type,sales_channel,total_claim_amount,vehicle_class,vehicle_size,vehicle_type,month
0,0,DK49336,Arizona,4809.216960,No,Basic,College,2011-02-18,Employed,M,...,9,Corporate Auto,Corporate L3,Offer3,Agent,292.800000,Four-Door Car,Medsize,A,2
1,1,KX64629,California,2228.525238,No,Basic,College,2011-01-18,Unemployed,F,...,1,Personal Auto,Personal L3,Offer4,Call Center,744.924331,Four-Door Car,Medsize,A,1
2,2,LZ68649,Washington,14947.917300,No,Basic,Bachelor,2011-02-10,Employed,M,...,2,Personal Auto,Personal L3,Offer3,Call Center,480.000000,SUV,Medsize,A,2
3,3,XL78013,Oregon,22332.439460,Yes,Extended,College,2011-01-11,Employed,M,...,2,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize,A,1
4,4,QA50777,Oregon,9025.067525,No,Premium,Bachelor,2011-01-17,Medical Leave,F,...,7,Personal Auto,Personal L2,Offer1,Branch,707.925645,Four-Door Car,Medsize,A,1

In [30]:
marketing.info()

<class 'pandas.DataFrame'>
RangeIndex: 10910 entries, 0 to 10909
Data columns (total 27 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   unnamed:_0                     10910 non-null  int64
 1   customer                       10910 non-null  str
 2   state                          10910 non-null  str
 3   customer_lifetime_value        10910 non-null  float64
 4   response                       10910 non-null  str
 5   coverage                       10910 non-null  str
 6   education                      10910 non-null  str
 7   effective_to_date              10910 non-null  str
 8   employmentstatus               10910 non-null  str
 9   gender                         10910 non-null  str
 10  income                         10910 non-null  int64
 11  location_code                  10910 non-null  str
 12  marital_status                 10910 non-null  str
 13  monthly_premium_auto           10910 non-null  int64
 14  months_since_last_claim        10910 non-null  float64
 15  months_since_policy_inception  10910 non-null  int64
 16  number_of_open_complaints      10910 non-null  float64
 17  number_of_policies             10910 non-null  int64
 18  policy_type                    10910 non-null  str
 19  policy                         10910 non-null  str
 20  renew_offer_type               10910 non-null  str
 21  sales_channel                  10910 non-null  str
 22  total_claim_amount             10910 non-null  float64
 23  vehicle_class                  10910 non-null  str
 24  vehicle_size                   10910 non-null  str
 25  vehicle_type                   10910 non-null  str
 26  month                          10910 non-null  int64
dtypes: float64(4), int64(6), str(17)
memory usage: 2.2 MB

In [31]:
#Crear pivot table para analizar customer lifetime value por sales channel
sales_pivot = pd.pivot_table(
    marketing,
    values='customer_lifetime_value',
    index='sales_channel',
    aggfunc='sum'
)

sales_pivot

               customer_lifetime_value
sales_channel
Agent                     3.305789e+07
Branch                    2.435920e+07
Call Center               1.736429e+07
Web                       1.269763e+07

In [34]:
sales_pivot.round(2)

               customer_lifetime_value
sales_channel
Agent                      33057887.85
Branch                     24359201.21
Call Center                17364288.37
Web                        12697632.90

In [35]:
#Analizar el average customer lifetime value
clv_pivot = pd.pivot_table(
    marketing,
    values='customer_lifetime_value',
    index='gender',
    columns='education',
    aggfunc='mean'
)

clv_pivot.round(2)

education  Bachelor  College   Doctor  High School or Below   Master
gender
F           7874.27  7748.82  7328.51               8675.22  8157.05
M           7703.60  8052.46  7415.33               8149.69  8168.83

1. You work at the marketing department and you want to know which sales channel brought the most sales in terms of total revenue. Using pivot, create a summary table showing the total revenue for each sales channel (branch, call center, web, and mail).
Round the total revenue to 2 decimal points.  Analyze the resulting table to draw insights.

2. Create a pivot table that shows the average customer lifetime value per gender and education level. Analyze the resulting table to draw insights.

## Bonus

You work at the customer service department and you want to know which months had the highest number of complaints by policy type category. Create a summary table showing the number of complaints by policy type and month.
Show it in a long format table.

*In data analysis, a long format table is a way of structuring data in which each observation or measurement is stored in a separate row of the table. The key characteristic of a long format table is that each column represents a single variable, and each row represents a single observation of that variable.*

*More information about long and wide format tables here: https://www.statology.org/long-vs-wide-data/*

In [ ]:
# Your code goes here